.\" Manpage for kevinrineer main index html
.\" Copyright, Kevin Rineer
.\" 
.TH KEVINRINEER 7 "2025-05-23" "Kevin Rineer Manual" "User Manuals"
.SH NAME
kevinrineer \- Main index for my manpage-style website
.SH SYNOPSIS
This is the main index for Kevin's website, styled as a Unix manual page.
.SH DESCRIPTION
This site is meant to emulate the look and feel of interating with Unix man pages. So, please navigate to the section you are interested in.

.SH CONTENTS
The site includes:

.TP
.B Curriculum Vitae
Man page formatted CV. Wow!
.UR
https://kevinrineer.com/cv/
.UE

.TP
.B About Me
For those who want to know how I try to present myself.
.UR
https://kevinrineer.com/aboutme/
.UE

.TP
.B Blog posts
Technical articles and essays, styled as man pages.
.UR
https://kevinrineer.com/blog/
.UE

.TP
.B Manpages
Complete and authentic Unix-format manpages, converted to HTML for web browsing.
.UR
https://kevinrineer.com/man/
.UE

.TP
.B Resources
Links, tools, and scripts related to the kevinrineer project.
.UR
https://kevinrineer.com/resources/
.UE

.SH SEE ALSO
kevinrineer.1(1), kevinrineer.3(3), kevinrineer.5(5)

.SH AUTHOR
Kevin Rineer <kevin@kevinrineer.com>

.SH "COPYRIGHT"
The style of the man-pages project is attributed to the authors of the Linux man-pages project.
The rest, Copyright, 2025 Kevin Rineer. All rights reserved.

