name: Personal Site Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Crucial for Tabi theme!

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Magic Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Flake checker
        uses: DeterminateSystems/flake-checker-action@main

      - name: Build Site with Nix
        # This runs 'zola build' inside your flake's devShell
        run: nix develop --command zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # This ensures the 'gh-pages' branch is used for hosting, which is automatically handled by this action.
          publish_branch: gh-pages
